# Generated by Django 5.0.8 on 2024-08-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('form_id', models.CharField(max_length=60)),
                ('submission_id', models.CharField(max_length=30)),
                ('field_name', models.CharField(max_length=30)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(max_length=30)),
            ],
        ),
    ]
