# Generated by Django 5.0.8 on 2024-08-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('form_id', models.CharField(max_length=30)),
                ('submission_id', models.CharField(max_length=30)),
                ('field_name', models.CharField(max_length=30)),
                ('field_value', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
    ]
