# Generated by Django 5.0.8 on 2024-08-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='id',
            new_name='uuid',
        ),
    ]
