# Generated by Django 5.0.8 on 2024-08-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_prospect_created_at_alter_prospect_form_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='form_id',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='submission_id',
            field=models.IntegerField(),
        ),
    ]
