# Generated by Django 5.0.8 on 2024-08-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_prospect_form_id_alter_prospect_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='created_at',
            field=models.DateField(),
        ),
    ]
